version: '3.8'

services:
  estadisticas-bardina:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estadisticas-bardina
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - DOMAIN=bardina.cperp.es
    volumes:
      # Volumen para logs de Nginx
      - ./logs:/var/log/nginx
      # Volumen para certificados SSL
      - ./ssl:/etc/nginx/ssl:ro
      # Volumen para validación de certbot
      - ./certbot-webroot:/var/www/certbot
    networks:
      - bardina-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Configuración adicional para producción
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Servicio para obtener certificados SSL
  certbot:
    image: certbot/certbot:latest
    container_name: certbot-bardina
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    # Solo se ejecuta cuando se llama manualmente
    profiles:
      - ssl
    command: >
      certonly --webroot
      --webroot-path=/var/www/certbot
      --email admin@bardina.cperp.es
      --agree-tos
      --no-eff-email
      --force-renewal
      -d bardina.cperp.es
      -d www.bardina.cperp.es
    networks:
      - bardina-network

networks:
  bardina-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  nginx-logs:
    driver: local
  ssl-certs:
    driver: local